### ISSUE TITLE
Bug Report: Failed installation for Node 10

### ISSUE THREAD

**Issue by hden** [googleapis/cloud-profiler-nodejs#329]
## Environment
- GKE
- Node `node:10-alpine`

```cloudbuild.yaml
---
steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - "debug"
      - "source"
      - "gen-repo-info-file"
  - name: node:10
    entrypoint: npm
    args: ["install"]
  - name: node:10
    entrypoint: npm
    args: ["run", "libphonenumber-metadata"]
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "--tag"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME"
      - "--build-arg"
      - "TAG=$TAG_NAME"
      - "."
images: ["gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME"]
```

```Dockerfile
FROM node:10-alpine
LABEL maintainer="Haokang Den <hden@toreta.in>"
ARG TAG
ENV TAG ${TAG:-latest}
ENV NODE_ENV production
WORKDIR /ds-stream
COPY . /ds-stream
CMD ["./run.sh"]
```

## Error

```
Error: The module '/ds-stream/node_modules/@google-cloud/profiler/build/Release/sampling_heap_profiler.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 57. This version of Node.js requires NODE_MODULE_VERSION 64. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/ds-stream/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/ds-stream/node_modules/@google-cloud/profiler/out/src/profilers/heap-profiler.js:19:37)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
```

**Comment by hden** [comment]
@ofrobots As you can see from the cloudbuild.yaml, it was build by the cloud builder (triggered by a GitHub release). My local `node_modules` was never committed to git.

Since the profiler requires python to build and we'd like to keep the image small (hence the alpine based image), I don't think a one-step build is possible.

FYI: the error message when running `npm install` within `node:10-alpine`

```
Step #1: > @google-cloud/profiler@0.2.2 install /ds-stream/node_modules/@google-cloud/profiler
Step #1: > node-gyp rebuild
Step #1: 
Step #1: gyp ERR! configure error 
Step #1: gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
Step #1: gyp ERR! stack at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
Step #1: gyp ERR! stack at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
Step #1: gyp ERR! stack at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
Step #1: gyp ERR! stack at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
Step #1: gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
Step #1: gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
Step #1: gyp ERR! stack at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
Step #1: gyp ERR! stack at FSReqWrap.oncomplete (fs.js:154:21)
Step #1: gyp ERR! System Linux 4.15.0-1023-gcp
Step #1: gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
Step #1: gyp ERR! cwd /ds-stream/node_modules/@google-cloud/profiler
Step #1: gyp ERR! node -v v10.13.0
Step #1: gyp ERR! node-gyp -v v3.8.0
Step #1: gyp ERR! not ok 
Step #1: npm WARN ds-stream@1.0.0 No description
Step #1: npm WARN ds-stream@1.0.0 No repository field.
Step #1: 
Step #1: npm ERR! code ELIFECYCLE
Step #1: npm ERR! errno 1
Step #1: npm ERR! @google-cloud/profiler@0.2.2 install: `node-gyp rebuild`
Step #1: npm ERR! Exit status 1
Step #1: npm ERR! 
Step #1: npm ERR! Failed at the @google-cloud/profiler@0.2.2 install script.
Step #1: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Step #1: 
Step #1: npm ERR! A complete log of this run can be found in:
Step #1: npm ERR! /root/.npm/_logs/2018-11-12T01_19_38_606Z-debug.log
Step #1: The command '/bin/sh -c npm install && npm run libphonenumber-metadata' returned a non-zero code: 1
```

IMHO we need to build it in either 1) cloud builder (using `node:10`) or 2) use a multistage build (also using `node:10`), Any suggestions?

**Comment by ofrobots** [comment]
Hi @hedn: I am not too familiar with Cloud Build, but looking at the details I do see now that you are "building" the container with `node:10` and then deploying the container with `node:10-alpine`.

You have to make sure that the deployment environment is identical to the the build environment. A native module compiled on `node:10` will not work when deployed to `node:10-alpine`. I am not too familiar with how Alpine linux works, but you will need the equivalent of the `build-essential` package from debian to be able to build native modules.

If you use `node:10` for deployment as well, things should work.

**Comment by hden** [comment]
Got it. Thanks.
