### ISSUE TITLE
tests failing while gyp tries to compile source code

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/cloud-profiler-nodejs#813]
```
node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v3.2.0/node-v83-win32-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for pprof@3.2.0 and node@14.19.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://storage.googleapis.com/cloud-profiler/pprof-nodejs/release/v3.2.0/node-v83-win32-x64-unknown.tar.gz 
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\hostedtoolcache\windows\node\14.19.0\x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\hostedtoolcache\windows\node\14.19.0\x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\hostedtoolcache\windows\node\14.19.0\x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\hostedtoolcache\windows\node\14.19.0\x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\hostedtoolcache\windows\node\14.19.0\x64\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\hostedtoolcache\windows\node\14.19.0\x64\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\hostedtoolcache\windows\node\14.19.0\x64\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:[10](https://github.com/googleapis/cloud-profiler-nodejs/runs/5679835207?check_suite_focus=true#step:4:10)58:16)
gyp ERR! System Windows_NT 10.0.20348
gyp ERR! command "C:\\hostedtoolcache\\windows\\node\\[14](https://github.com/googleapis/cloud-profiler-nodejs/runs/5679835207?check_suite_focus=true#step:4:14).[19](https://github.com/googleapis/cloud-profiler-nodejs/runs/5679835207?check_suite_focus=true#step:4:19).0\\x64\\node.exe" "C:\\hostedtoolcache\\windows\\node\\14.19.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\a\\cloud-profiler-nodejs\\cloud-profiler-nodejs\\node_modules\\pprof\\build\\node-v83-win[32](https://github.com/googleapis/cloud-profiler-nodejs/runs/5679835207?check_suite_focus=true#step:4:32)-x64-unknown\\pprof.node" "--module_name=pprof" "--module_path=D:\\a\\cloud-profiler-nodejs\\cloud-profiler-nodejs\\node_modules\\pprof\\build\\node-v83-win32-x64-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd D:\a\cloud-profiler-nodejs\cloud-profiler-nodejs\node_modules\pprof
gyp ERR! node -v v14.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Comment by nolanmar511** [comment]
This repo depends on a library with a native portion which does not test against windows and does not have pre-built windows binaries (https://github.com/googleapis/cloud-profiler-nodejs#prerequisites).

Since Cloud Profiler does not formally running this agent on a non-linux operating system (see https://cloud.google.com/profiler/docs/about-profiler#environment_and_languages), removing tests against windows is the path forward I would reccomend.

**Comment by SurferJeffAtGoogle** [comment]
This will be fixed when @alexander-fenster removes the Windows tests.

**Comment by amchiclet** [comment]
Windows tests are removed by this [PR](https://github.com/googleapis/cloud-profiler-nodejs/pull/830).
